# Generated by Django 5.1.15 on 2026-07-14 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0002_clinic_settings"),
        ("encounters", "0002_vitals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("void_reason", models.TextField(blank=True, editable=False)),
                ("presenting_complaint", models.TextField(blank=True)),
                ("clinical_notes", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("signed", "Signed")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                ("amendment_reason", models.TextField(blank=True, editable=False)),
                (
                    "amended_from",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amended_by",
                        to="clinical.consultation",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "diagnoses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("free_text", models.CharField(blank=True, max_length=255)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="clinical.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinical.diagnosis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "consultation diagnoses",
            },
        ),
        migrations.AddConstraint(
            model_name="consultation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("amended_from__isnull", True), ("voided_at__isnull", True)
                ),
                fields=("encounter",),
                name="one_root_consultation_per_encounter",
            ),
        ),
        migrations.AddConstraint(
            model_name="consultationdiagnosis",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("diagnosis__isnull", False),
                    models.Q(("free_text", ""), _negated=True),
                    _connector="OR",
                ),
                name="diagnosis_coded_or_free_text",
            ),
        ),
    ]
