# Generated by Django 5.1.15 on 2026-07-16 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_referralletter_sicknote_prescription_and_more"),
        ("clinics", "0002_clinic_settings"),
        ("pharmacy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="medication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="pharmacy.medication",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="clinical.prescription",
            ),
        ),
        migrations.AddField(
            model_name="referralletter",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="referralletter",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to="clinical.consultation",
            ),
        ),
        migrations.AddField(
            model_name="referralletter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralletter",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sicknote",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="sicknote",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sick_notes",
                to="clinical.consultation",
            ),
        ),
        migrations.AddField(
            model_name="sicknote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sicknote",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="prescriptionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("medication__isnull", False),
                    models.Q(("medication_note", ""), _negated=True),
                    _connector="OR",
                ),
                name="prescription_item_coded_or_note",
            ),
        ),
    ]
