# Generated by Django 5.1.15 on 2026-07-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
