# Generated by Django 5.1.15 on 2026-07-13 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("void", "Void"),
                            ("read", "Read"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("model_label", models.CharField(editable=False, max_length=100)),
                (
                    "object_pk",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("changes", models.JSONField(blank=True, default=dict, editable=False)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["model_label", "object_pk"],
                        name="core_auditl_model_l_76293c_idx",
                    ),
                    models.Index(
                        fields=["user", "at"], name="core_auditl_user_id_041bc8_idx"
                    ),
                ],
            },
        ),
    ]
