# Generated by Django 5.1.15 on 2026-07-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cliniccounter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("void", "Void"),
                    ("read", "Read"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Failed"),
                    ("break_glass", "Break Glass"),
                ],
                editable=False,
                max_length=16,
            ),
        ),
    ]
