# Generated by Django 5.1.15 on 2026-07-14 10:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0002_clinic_settings"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("void_reason", models.TextField(blank=True, editable=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk In"),
                            ("follow_up", "Follow Up"),
                            ("emergency", "Emergency"),
                            ("appointment", "Appointment"),
                            ("anc", "Anc"),
                        ],
                        default="walk_in",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_triage", "In Triage"),
                            ("awaiting_doctor", "Awaiting Doctor"),
                            ("in_consultation", "In Consultation"),
                            ("at_lab", "At Lab"),
                            ("at_pharmacy", "At Pharmacy"),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("closed", "Closed"),
                            ("left_without_being_seen", "Lwbs"),
                        ],
                        default="waiting",
                        max_length=25,
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounters",
                        to="patients.patient",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["arrived_at"],
                "permissions": [
                    (
                        "close_with_balance",
                        "Can close an encounter with an outstanding balance",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["clinic", "status"],
                        name="encounters__clinic__2f02d0_idx",
                    )
                ],
            },
        ),
    ]
