# Generated by Django 5.1.15 on 2026-07-17 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_invoiceitem_lab_order"),
        ("clinics", "0002_clinic_settings"),
        ("laboratory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "permissions": [
                    ("apply_discount", "Can apply a discount to an invoice")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "permissions": [("reverse_payment", "Can reverse a recorded payment")]
            },
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="discount_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_type", "discount"), _negated=True),
                    models.Q(
                        ("unit_price__lt", 0),
                        ("service_item__isnull", True),
                        ("lab_order__isnull", True),
                        models.Q(("discount_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="discount_lines_negative_sourceless_reasoned",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_type", "service"), _negated=True),
                    models.Q(("unit_price__gte", 0), ("discount_reason", "")),
                    _connector="OR",
                ),
                name="service_lines_nonnegative_unreasoned",
            ),
        ),
    ]
